server:
  port: 8088

spring:
  application:
    name: music
  datasource:
    name: musicdata
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      web:
        group:
          dao: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml